services:
  postgres:
    image: postgres:15-alpine
    ports:
      - $POSTGRES_PORT:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
